In [2]:
import numpy as np

In [3]:
np.random.permutation(np.array([
    [1,2,3,4,5],
    [6,7,8,9,1],
    [2,3,4,5,6],
    [7,8,9,1,2]
]))

array([[7, 8, 9, 1, 2],
       [2, 3, 4, 5, 6],
       [6, 7, 8, 9, 1],
       [1, 2, 3, 4, 5]])

In [4]:
rng=np.random.default_rng()
a=rng.random(25)
print(a)
np.sum(a)

[0.40809954 0.61239942 0.92152078 0.21481452 0.36894661 0.74033781
 0.62166431 0.8747971  0.39736734 0.63515978 0.89219123 0.04544284
 0.58448143 0.35606478 0.12863491 0.67436929 0.06335935 0.07120853
 0.62392729 0.66115802 0.4654751  0.19125707 0.16337114 0.98512486
 0.02534932]


np.float64(11.726522366078104)

In [5]:
np.min(a)

np.float64(0.025349318417052236)

In [6]:
np.max(a)

np.float64(0.9851248594970693)

In [24]:
x=np.array([
    [1,2,3,4,5],
    [1,2,3,4,6],
    [1,2,3,4,7],
    [1,2,0,0,10]
])
x 

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  6],
       [ 1,  2,  3,  4,  7],
       [ 1,  2,  0,  0, 10]])

In [25]:
x.max(axis=1) #for rows

array([ 5,  6,  7, 10])

In [26]:
x.max(axis=0) #for columns

array([ 1,  2,  3,  4, 10])

In [15]:
np.nanmax(x)

np.int64(980)