In [2]:
import numpy as np

In [3]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros(10,dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [7]:
np.ones((4,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.full((5,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.linspace(0,360,13)

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
       330., 360.])

In [14]:
np.random.random((3,3))

array([[0.9449644 , 0.82047401, 0.78107483],
       [0.76221526, 0.20529167, 0.59254947],
       [0.20598376, 0.99203892, 0.5979687 ]])

In [15]:
np.random.normal(0,1,(3,3))

array([[-0.16533535,  0.96242363, -0.00462158],
       [ 0.20815658, -1.04611075,  2.9725143 ],
       [-1.1116646 ,  0.37556203,  0.30828622]])

In [16]:
np.random.randint(1,10,(5,5))

array([[1, 7, 4, 7, 7],
       [2, 6, 8, 7, 7],
       [3, 5, 3, 9, 6],
       [3, 2, 5, 5, 1],
       [1, 2, 7, 2, 6]], dtype=int32)

In [17]:
np.eye(6,6,0,int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [24]:
np.empty(6)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 4.67293691e-307,
       1.42413555e-306, 1.78019082e-306])