## Sorting Arrays

In [2]:
import random
arr=[random.randint(0,100) for _ in range(10)]
print(arr)
sorted(arr)

[1, 96, 32, 76, 2, 47, 33, 3, 54, 71]


[1, 2, 3, 32, 33, 47, 54, 71, 76, 96]

In [3]:
arr.sort()
arr

[1, 2, 3, 32, 33, 47, 54, 71, 76, 96]

In [4]:
sorted("hello")

['e', 'h', 'l', 'l', 'o']

In [5]:
import numpy as np

array=np.array([1,4,5,3,7])
np.sort(array)

array([1, 3, 4, 5, 7])

In [6]:
array2=np.array([2,5,6,7,4,3,1])
np.argsort(array2)

array([6, 0, 5, 4, 1, 2, 3])

In [7]:
array2[np.argsort(array2)]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
randArr=np.random.default_rng(seed=10)
randArr2=randArr.integers(0,10,(4,5))
randArr2

array([[7, 9, 2, 2, 7],
       [8, 5, 1, 8, 5],
       [1, 1, 4, 6, 4],
       [8, 0, 4, 5, 9]])

In [9]:
np.sort(randArr2,0)

array([[1, 0, 1, 2, 4],
       [7, 1, 2, 5, 5],
       [8, 5, 4, 6, 7],
       [8, 9, 4, 8, 9]])

In [10]:
np.sort(randArr2,1)

array([[2, 2, 7, 7, 9],
       [1, 5, 5, 8, 8],
       [1, 1, 4, 4, 6],
       [0, 4, 5, 8, 9]])

In [11]:
np.sort(randArr2)

array([[2, 2, 7, 7, 9],
       [1, 5, 5, 8, 8],
       [1, 1, 4, 4, 6],
       [0, 4, 5, 8, 9]])

In [12]:
lst=randArr.integers(0,10,(4,6))
lst

array([[2, 8, 0, 3, 7, 5],
       [9, 7, 9, 8, 1, 9],
       [8, 1, 9, 7, 3, 1],
       [3, 9, 7, 2, 4, 8]])

In [16]:
np.partition(lst,3,0)

array([[2, 1, 0, 2, 1, 1],
       [3, 7, 7, 3, 3, 5],
       [8, 8, 9, 7, 4, 8],
       [9, 9, 9, 8, 7, 9]])

In [14]:
a=randArr.random((10,2))
print(a)
a[:,1]

[[0.30631787 0.96983037]
 [0.51783421 0.32247456]
 [0.28243352 0.605865  ]
 [0.33376446 0.67864877]
 [0.15442507 0.24977552]
 [0.86989425 0.60036782]
 [0.26198306 0.1494149 ]
 [0.13678915 0.24892094]
 [0.38282467 0.64907906]
 [0.83756376 0.77603195]]


array([0.96983037, 0.32247456, 0.605865  , 0.67864877, 0.24977552,
       0.60036782, 0.1494149 , 0.24892094, 0.64907906, 0.77603195])