# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.



In [2]:
# first
import numpy as np
import random as r

arr1=np.array([[r.randint(1,21) for j in range(5)] for i in range(5)])

arr1[: ,3]=1

print(type(arr1))
print(arr1)

# second
arr2 = np.array([[(i + j * 4)+1 for i in range(4)] for j in range(4)])
for i in range(len(arr2)):
        arr2[i][i]=0
print(arr2)


<class 'numpy.ndarray'>
[[10 14 14  1  7]
 [ 6 12 18  1  4]
 [18 15  1  1 11]
 [20 21 20  1 13]
 [ 5  8 16  1  7]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.



In [ ]:
# f
arr=np.array([[(i+j*6)+1 for i in range(6)] for j in range(6) ])
print(arr)
new_arr=arr[2:5,1:4]

print(new_arr)

# s
rand_arr=np.array([[r.randint(1,100) for j in range(5)] for i in range(5)])
print(rand_arr)
rand_arr=rand_arr[1:4,1:4]
print(rand_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[ 28  42   2  42  43]
 [ 63   2  43  67  28]
 [ 13  28  54  87  31]
 [ 50  75  23  19  31]
 [ 74 100  87  93  76]]
[[ 2 43 67]
 [28 54 87]
 [75 23 19]]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.



In [ ]:
# f
rand_arr1=np.array([[r.randint(1,100) for j in range(4)] for i in range(3)])
rand_arr2=np.array([[r.randint(1,100) for j in range(4)] for i in range(3)])


print(rand_arr1,"\n")
print(rand_arr2,"\n")
print(rand_arr1 + rand_arr2,"\n")
print(rand_arr1 - rand_arr2,"\n")
print(rand_arr1 * rand_arr2,"\n")
print(rand_arr1 / rand_arr2,"\n")

# s
fcfArr=np.array([[(i+j*4)+1 for i in range(4)] for j in range(4)])
print("\n \n",fcfArr)
print("\n",np.sum(fcfArr,axis=1))
print("\n",np.sum(fcfArr,axis=0))

[[98 42  8 92]
 [14 17 90  2]
 [ 2  9 31 96]] 

[[39  1 71 51]
 [67 39  8  9]
 [57 32 87 40]] 

[[137  43  79 143]
 [ 81  56  98  11]
 [ 59  41 118 136]] 

[[ 59  41 -63  41]
 [-53 -22  82  -7]
 [-55 -23 -56  56]] 

[[3822   42  568 4692]
 [ 938  663  720   18]
 [ 114  288 2697 3840]] 

[[2.51282051e+00 4.20000000e+01 1.12676056e-01 1.80392157e+00]
 [2.08955224e-01 4.35897436e-01 1.12500000e+01 2.22222222e-01]
 [3.50877193e-02 2.81250000e-01 3.56321839e-01 2.40000000e+00]] 


 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 [10 26 42 58]

 [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).



In [ ]:
# f
rng=np.random.default_rng(50)
arr=rng.integers(1,100,(5,5))

print(arr)
print(f"mean: {np.mean(arr)}")
print(f"median: {np.median(arr)}")
print(f"standard deviation: {np.std(arr)}")
print(f"variance: {np.var(arr)}")


# s 
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

[[78 78 71 83 82]
 [55 25 97 83 24]
 [28 65 67  7 96]
 [56  2 40 65 27]
 [69 98 62 40 19]]
mean: 56.68
median: 65.0
standard deviation: 28.04099855568628
variance: 786.2976


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.



In [16]:
# f 
array=np.random.default_rng(seed=1701)
array1=array.integers(1,10,(3,3))
array2=array.integers(1,10,(3,1))
print(array1+array2)


# s 
array1=array.integers(1,10,(4,4))
array2=array.integers(1,10,(4,1))
print("\n",array1-array2)

[[17 12  9]
 [ 7 12 11]
 [ 5  3  5]]

 [[ 2  3  0  0]
 [-2  1 -4 -4]
 [-3 -3 -7  0]
 [-2  0 -3 -3]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.



In [3]:
# f 
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

# s 
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Original matrix:
[[ 5  8  6]
 [ 3  3  6]
 [10  7  2]]
Determinant: 198.00000000000017
Inverse:
[[-0.18181818  0.13131313  0.15151515]
 [ 0.27272727 -0.25252525 -0.06060606]
 [-0.04545455  0.22727273 -0.04545455]]
Eigenvalues: [16.48945913+0.j         -3.24472956+1.21630632j -3.24472956-1.21630632j]
Array 1:
[[6 9 8]
 [4 3 4]]
Array 2:
[[9 8]
 [1 4]
 [3 4]]
Matrix multiplication result:
[[ 87 116]
 [ 51  60]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).



In [4]:
# f
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

# s 
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Original array:
[[ 6 11 17  5 18]
 [13  7 19  5  8]
 [ 5 19 16  6  9]
 [ 3 20 20  8  6]
 [14  4 16  4 12]]
Flattened array:
[ 6 11 17  5 18 13  7 19  5  8  5 19 16  6  9  3 20 20  8  6 14  4 16  4
 12]
Reshaped array:
[[ 6 11 17  5 18]
 [13  7 19  5  8]
 [ 5 19 16  6  9]
 [ 3 20 20  8  6]
 [14  4 16  4 12]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.



In [5]:
# f 
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

# s 
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[12 17  2  3 13]
 [ 5 12 13 18  3]
 [10  9  6  2 10]
 [19  3  9 20  3]
 [12  1 13  6  6]]
Corner elements:
[12 13 12  6]
Original array:
[[13 16  8  7]
 [10 14  8 10]
 [20 13 20 12]
 [10 17  3  1]]
Modified array:
[[10 10  8  7]
 [10 10  8 10]
 [10 10 10 10]
 [10 10  3  1]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [6]:
# f 
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

# s 
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]
Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [7]:
# f 
import numpy.ma as ma

array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

# s 
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 1 17 15  6]
 [15  9 14  9]
 [ 2  6  1  5]
 [12  5  6 14]]
Masked array:
[[1 -- -- 6]
 [-- 9 -- 9]
 [2 6 1 5]
 [-- 5 6 --]]
Sum of unmasked elements: 50
Original array:
[[ 1 10 12]
 [ 5 15  6]
 [19  6 17]]
Masked array:
[[-- 10 12]
 [5 -- 6]
 [19 6 --]]
Modified masked array:
[[ 9 10 12]
 [ 5  9  6]
 [19  6  9]]
