In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr.shape

(5,)

In [3]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.reshape(5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
arr.shape

(5,)

In [8]:
arr2 = np.arange(0, 10)

In [9]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr2.reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])